name: muhportal
description: A Flutter application to monitor and control various portals (doors and locks) via MQTT over WebSockets.
publish_to: 'none'
version: 2.4.0+6

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # MQTT client for WebSocket connection
  mqtt_client: ^10.2.0
  
  # Persistent storage
  shared_preferences: ^2.2.2
  
  # Material Design icons
  cupertino_icons: ^1.0.6
  
  # Internationalization
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
